services:
  postgres:
    image: postgres:15
    container_name: fraglify-postgres
    restart: always
    environment:
      POSTGRES_DB: fraglify
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
